name: Daily Push To Google from Jira

on: 
  schedule:
    - cron:  '0 */8 * * *' # this will run three times a day (every 8 hours)
  workflow_dispatch: # this allows the workflow to be run manually from the Actions tab

jobs:
  run-container-and-send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Credentials
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}" | base64 --decode > gcp_creds.json
      env:
        GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}

    - name: Run Docker Container
      run: |
          docker run --rm -v $(pwd)/gcp_creds.json:/tmp/gcp_creds.json \
          -e GOOGLE_APPLICATION_CREDENTIALS='/tmp/gcp_creds.json' \
          -e JIRA_TOKEN=${{ secrets.JIRA_TOKEN }} \
          -e GOOGLE_SHEETS_TOKEN=${{ secrets.GOOGLE_SHEETS_TOKEN }} \
          riscvintl/jira-to-google:latest
